addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"    % "1.1.1")
addSbtPlugin("io.spray"            % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"         % "0.6.1")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager" % "1.9.4")
addSbtPlugin("com.github.sbt"      % "sbt-release"         % "1.1.0")
// addSbtPlugin("org.scala-js"        % "sbt-scalajs"         % "1.10.0")
addCompilerPlugin("com.olegpy"    %% "better-monadic-for"  % "0.3.1")
